export const GET_INSTRUMENTATIONS = 'GET_INSTRUMENTATIONS';
export const GET_INSTRUMENTATIONS_SUCCESS = 'GET_INSTRUMENTATIONS_SUCCESS';

export const GET_MEASUREMENTS = 'GET_MEASUREMENTS';
export const GET_MEASUREMENTS_SUCCESS = 'GET_MEASUREMENTS_SUCCESS';
