CREATE TABLE measurement (
  id SERIAL PRIMARY KEY,
  source CHARACTER VARYING NOT NULL,
  timestamp TIMESTAMP NOT NULL,
  type CHARACTER VARYING NOT NULL,
  value CHARACTER VARYING NOT NULL,
  unit CHARACTER VARYING NOT NULL
)